apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argo
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps
    repoURL: https://github.com/bernardolsp/descomplicando-gitops-no-kubernetes-argocd.git
    targetRevision: feat/day-extras
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 
