# test
argocd:
  randomLogger:
    enabled: true
    replicas: 10
  randomLogger:
    enabled: true
  prometheus:
    enabled: true
    ingress: "https://prometheus-mycompany.com"
  grafana:
    enabled: true
    ingress: "https://grafana-mycompany.com"