apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.18.0
      helm:
        valueFiles:
          - $values/cert-manager/values.yaml

    - repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
