apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: girus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://EduardoThums-Girus-PICK.github.io/helm
      targetRevision: 1.0.8
      chart: girus
      helm:
        valueFiles:
          - $values/girus/values/girus.yaml
    
    - repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
      targetRevision: main
      ref: main

  destination:
    namespace: default
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      selfHeal: true # ensures tha the state of the application in the repo is respected
    syncOptions:
      - CreateNamespace=true
