apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.12.3
      chart: ingress-nginx
      helm:
        valueFiles:
          - $values/girus/ingress-nginx/values.yaml

    - repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
      targetRevision: main
      ref: values

  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true # ensures tha the state of the application in the repo is respected
    syncOptions:
      - CreateNamespace=true
