apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: building-cloned-template-
  namespace: argo
spec:
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


  volumes:
  - name: docker-credentials
    secret:
      secretName: docker-credentials
      items: 
      - key: config.json
        path: config.json

  entrypoint: clone

  templates:
  - name: clone
    steps:
    - - name: cloneRepo
        arguments: 
          parameters:
          - name: repo
            value: https://github.com/bernardolsp/go-todo.git
        templateRef:
          name: github-clone
          template: github-clone
    - - name: get-and-test
        templateRef: 
          name: get-and-test
          template: get-and-test
    - - name: docker-build
        templateRef: 
          name: docker-build
          template: docker-build
        arguments:
          parameters:
          - name: destination
            value: devlopesbernardo/go-todo 

