apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
        revision: main
        files:
          - path: applicationSets/configs/*.json
  template:
    metadata:
      name: 'app-of-apps-{{.environment}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
        targetRevision: main
        path: 'applicationSets/app-of-apps'
        helm:
          valuesObject:
            - environment: '{{.environment}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.environment}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
