apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
              revision: main
              files:
                - path: applicationSets/configs/*.json
          - git:
              repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
              revision: main
              pathParamPrefix: app
              directories:
                - path: applicationSets/apps/*/helm

  template:
    metadata:
      name: '{{index .app.path.segments 2}}-{{.environment}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
          targetRevision: main
          path: '{{.app.path.path}}'
          helm:
            valuesObject:
              argocd:
                environment: '{{.environment}}'
            valueFiles:
              - $values/applicationSets/values.yaml
          
        - repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
          targetRevision: main
          ref: values
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.environment}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
