apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
        revision: main
        directories:
          - path: applicationSets/apps/*/helm
  template:
    metadata:
      name: '{{index .path.segments 2}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
          targetRevision: main
          path: '{{.path.path}}'
          helm:
            valueFiles:
              - $values/applicationSets/values.yaml

        - repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
          targetRevision: main
          ref: values

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: guestbook
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
