apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        github:
          owner: EduardoThums
          repo: descomplicando-gitops-no-kubernetes-argocd
          tokenRef:
            key: token
            secretName: github-secret
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'stack-apps-{{.branch_slug}}-{{.number}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/EduardoThums/descomplicando-gitops-no-kubernetes-argocd.git
        targetRevision: '{{.head_sha}}'
        path: 'giropops-senhas/helm'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.branch_slug}}-{{.number}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
