apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-todo
  namespace: argo
spec:
  project: 'default'
  source:
    plugin: {}
    repoURL: https://github.com/bernardolsp/go-todo
    targetRevision: HEAD
    path: "."
  destination:
    namespace: go-todo
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

